backend:
  name: github
  repo: chanmaxsolutions/chanmax-new-website
  branch: main
  base_url: https://chanmax-new-website.vercel.app
  auth_endpoint: api/auth
  auth_scope: repo
  accept_roles:
    - admin
    - editor
  allowed_users:
    - chanmaxsolutions
    - prashankhan63   # Add your other GitHub username here

media_folder: "public/uploads"
public_folder: "/uploads"

# ... rest of your collections

local_backend: true

collections:
  - name: "case-studies"
    label: "Case Studies"
    folder: "content/case-studies"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Industry", name: "industry", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}